style = "sciml"
whitespace_ops_in_indices = true
remove_extra_newlines = true
always_for_in = true
whitespace_typedefs = true
normalize_line_endings = "unix"
short_to_long_function_def = false
format_markdown = true
